In [ ]:
import numpy as np
d1arr=np.array([2,3,4,5,6])
d2arr=np.array([[2,4,3,5,6],[4,8,9,0,6]])
d3arr=np.array([[[4,6,7,8,8],[3,4,5,6,7],[4,5,3,4,3]]])
print("1-D\n",d1arr)
print("2-D\n",d2arr)
print("3-D\n",d3arr)

1-D
 [2 3 4 5 6]
2-D
 [[2 4 3 5 6]
 [4 8 9 0 6]]
3-D
 [[[4 6 7 8 8]
  [3 4 5 6 7]
  [4 5 3 4 3]]]


In [11]:
import numpy as np
# Array of 150 random integers between 1 and 1000
arr=np.random.randint(1,1000,size=150)
even_num=arr[arr%2==0]
print("Even Numbers\n",even_num)
# to print prime numbers only
def is_prime(num):
    if num<2:
        return False
    for i in range(2,int(num**0.5)+1):
        if num%i==0:
            return False
    return True

prime_num=np.array([num for num in arr if is_prime(num)])
print("Prime Numbers\n",prime_num)
def get_multiples(array,number):
    return array[array %number==0]
n=int(input("\nEnter a number to find its multiples: "))
multiples=get_multiples(arr, n)
print(f"\nMultiples of {n}:\n",multiples)




Even Numbers
 [832 288 956 126 168 762 502 330 394 418 834 326 990 100 978 586 108 278
 156 956 368 160 242 534 680 854 718 554 594 680 100 766 506 938 702 726
 934 602 366 422 408 642 426 390 222  32 792 816 256 282 278 510 110 352
 724 980 834 870  10 402 468 228 534 486 486 670 178 618 134  86 268 708
 794 810]
Prime Numbers
 [487 523 487  53  71 227 283 509 269 877  59 719 263  19 389 241 431 857
 911 593 809 571 829 829 457]

Enter a number to find its multiples: 6

Multiples of 6:
 [288 126 168 762 330 834 990 978 108 156 534 594 702 726 366 408 642 426
 390 222 792 816 282 510 834 870 402 468 228 534 486 486 618 708 810]
