##Name: Muhammad Sadeem Choudhary
##sap id: 66385

###1. Create a following list:
###2, 6, 11, 24, 8, 45, 25, 60
###a) Delete last element of the list
###b) Add 22 value at index 3 of the list
###c) Create an ndarray object by using this list.


In [8]:
import numpy as np
array_1=np.array([2,6,11,24,8,45,25,60])
print(array_1)

[ 2  6 11 24  8 45 25 60]


In [10]:
array_1=np.delete(array_1,-1)
print(array_1)

[ 2  6 11 24  8 45 25]


In [11]:
array_1=np.insert(array_1,3,22)
print(array_1)

[ 2  6 11 22 24  8 45 25]


In [12]:
 array_2=np.array(array_1)
 print(array_2)


[ 2  6 11 22 24  8 45 25]


###2. Create a 2-D array and a 3-D array. Split the 2-D array into three 2-D arrays along rows.

In [20]:

array_3=np.array([[2,6,11,24],[8,45,25,60]])
print("3-D array\n",array_3)
array_4=np.array([[[2,6,11,24],[8,45,25,60],[2,6,11,24]]])
print("3-D array\n",array_4)


3-D array
 [[ 2  6 11 24]
 [ 8 45 25 60]]
3-D array
 [[[ 2  6 11 24]
  [ 8 45 25 60]
  [ 2  6 11 24]]]


In [30]:
array_5=np.array_split(array_3, 3, axis=0)
print("Splitting array_3 into three 2D arrays along rows:\n", array_5)
print("Array 1\n",array_5[0])
print("Array 2\n",array_5[1])
print("Array 3\n",array_5[2])

Splitting array_3 into three 2D arrays along rows:
 [array([[ 2,  6, 11, 24]]), array([[ 8, 45, 25, 60]]), array([], shape=(0, 4), dtype=int64)]
Array 1
 [[ 2  6 11 24]]
Array 2
 [[ 8 45 25 60]]
Array 3
 []


###3. Find the indexes where the values are even

In [31]:
array_6=np.array([2,6,11,24,8,45,25,60])
print(array_6)
indexes = np.where(array_6%2==0)
print("Indexes where values are even:", indexes)


[ 2  6 11 24  8 45 25 60]
Indexes where values are even: (array([0, 1, 3, 4, 7]),)


###4. Create a filter array that will return only values higher than 55

In [34]:
array_7=np.array([2,6,11,74,8,45,25,60])
filter_array=array_7>55
filtered_values=array_7[filter_array]
print(filtered_values)

[74 60]


###5. Create a 3x3 matrix with values ranging from 2 to 10, convert array to a float type. Write a Python program to find the maximum and minimum value of flattened array.

In [38]:
array_8=np.arange(2,11).reshape(3,3)
print(array_8)
array_9=array_8.astype(float)
print(array_9)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [39]:
max_value=np.max(array_9)
min_value=np.min(array_9)
print("Maximum value:",max_value)
print("Minimum value:",min_value)



Maximum value: 10.0
Minimum value: 2.0
